version: '3'

services:
  postgres:
    image: postgres

    networks:
      - melody

    environment:
      POSTGRES_USER: MelodyUser
      POSTGRES_PASSWORD: MelodyDevelopment
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: melody

    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis

    networks:
      - melody

  memcached:
    image: memcached

    networks:
      - melody

  services:
    command: bin/development-server
    build: services

    links:
      - postgres
      - redis:redis
      - memcached:memcached

    environment:
      - MELODY_SETTINGS_MODULE=melody.settings.compose

    networks:
      - melody

    volumes:
      - './services:/opt/services'

  web:
    command: npm run compose
    build: clients/web

    networks:
      - melody

    volumes:
      - './clients/web:/opt/web'

  nginx:
    build: tools/nginx

    links:
      - services
      - web

    networks:
      - melody

    ports:
      - 8080:80

networks:
  melody:
    driver: bridge
