version: '3'

services:
  postgres:
    image: postgres

    networks:
      - metanic

    environment:
      POSTGRES_USER: MelodyUser
      POSTGRES_PASSWORD: MelodyDevelopment
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: metanic

    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis

    networks:
      - metanic

  memcached:
    image: memcached

    networks:
      - metanic

  services:
    command: bin/development-server
    build: services

    links:
      - postgres
      - redis:redis
      - memcached:memcached

    environment:
      - MELODY_SETTINGS_MODULE=metanic.settings.compose

    networks:
      - metanic

    volumes:
      - './services:/opt/services'

  web:
    command: npm run compose
    build: clients/web

    networks:
      - metanic

    volumes:
      - './clients/web:/opt/web'

  nginx:
    build: tools/nginx

    links:
      - services
      - web

    networks:
      - metanic

    ports:
      - 8080:80

networks:
  metanic:
    driver: bridge
